### ISSUE TITLE
Bottleneck error checking breaks on Test Tube grid search

### ISSUE THREAD

**Issue by yifr** [ebatty/behavenet#11]
I set up `n_ae_latents` as a list. It gets added to the parser as a 'tunable' argument with options but since it doesn't have a default value, `namespace.n_ae_latents` gets set to `None`, and I receive this error:

```
  File "behavenet/fitting/hyperparam_utils.py", line 83, in add_dependent_params
    * arch_dict['ae_encoding_y_dim'][-1]) < namespace.n_ae_latents:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

This check passes when I set `n_ae_latents` to a single int, rather than a list.  

(*Only relevant on develop branch*)

**Comment by themattinthehatt** [comment]
Hey Yoni, this should be fixed on the latest develop branch, but many other changes have taken place in the meantime so you might not want to pull all updates. See the commit [here](https://github.com/ebatty/behavenet/commit/44ec96498047245b4fe9c8694d7687672691d327). Basically you can just get rid of this check for now, as it happens in the AE grid search anyways.

**Comment by yifr** [comment]
Oh, awesome - thank you!
