### ISSUE TITLE
Slurm's srun command passes hyperparameters as command line args instead of config files 

### ISSUE THREAD

**Issue by yifr** [ebatty/behavenet#12]
I'm trying to run some decoding trials using slurm. I have a slurm config file that looks like this:

```
#!/bin/bash
#SBATCH --job-name=decoder_grid_search    # Job name
#SBATCH --mail-type=END,FAIL          # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=yoniifriedman@gmail.com   # Where to send mail
#SBATCH --time=00:05:00               # Time limit hrs:min:sec
#SBATCH --account=zi
#SBATCH --nodes 1
#SBATCH -c 1
```

The job fails, with this message:
<img width="745" alt="Screen Shot 2020-06-23 at 6 49 04 PM" src="https://user-images.githubusercontent.com/26826815/85900106-398de280-b7cd-11ea-85aa-2d5cce6dc575.png">

Here's the srun command where the arguments are coming from:
<img width="1435" alt="Screen Shot 2020-06-23 at 6 48 51 PM" src="https://user-images.githubusercontent.com/26826815/85900105-38f54c00-b7cd-11ea-8fb3-0c3abbecb0ee.png">

Should the srun command contain the typical config command line arguments instead of the hyperparameters themselves?

The __get_run_command function for context:

```
def __get_run_command(self, trial, slurm_cmd_script_path, timestamp, exp_i, on_gpu):
        trial_args = self._SlurmCluster__get_hopt_params(trial)
        trial_args = '{} --{} {} --{} {}'.format(trial_args,
                                                 HyperOptArgumentParser.SLURM_CMD_PATH,
                                                 slurm_cmd_script_path,
                                                 HyperOptArgumentParser.SLURM_EXP_CMD,
                                                 exp_i)

        cmd = 'srun {} {} {}'.format(self.python_cmd, self.script_name, trial_args)
        return cmd
```

**Comment by themattinthehatt** [comment]
@ebatty any input on this? I haven't used behavenet with slurm before
