### ISSUE TITLE
What is the shape of the 'labels' dataset in the HDF5 file?

### ISSUE THREAD

**Issue by cxrodgers** [ebatty/behavenet#13]
I'm following these instructions to make my HDF5 file:
https://behavenet.readthedocs.io/en/latest/source/data_structure.html#data-structure

I know that there is also a "labels" dataset with joint coordinates. What is the shape of this suppose to be? Is it (n_frames, 2, n_labels), with the second axis being "x" and "y" coordinates? Or (n_frames, n_labels, 2)?

thanks!

**Comment by cxrodgers** [comment]
By trial and error, it seems like it is just (n_frames, 2 * n_joints)!

**Comment by themattinthehatt** [comment]
Hey Chris, if you look in the bottom part of the left column on readthedocs you should see a button that says `v:latest`; if you click on this you can change which code version you are referencing. Switch over to the `develop` branch and you'll get updated documentation, which includes some info on the labels.

That being said, I just realized that even the label documentation isn't super clear, so I'll make sure to update that!
