### ISSUE TITLE
ae_grid_search doesn't parse n_ae_latents when it's a list 

### ISSUE THREAD

**Issue by cxrodgers** [ebatty/behavenet#14]
If "n_ae_latents" is a list in ae_model.json, then I get this cryptic error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/dev/behavenet/behavenet/fitting/ae_grid_search.py in <module>
    126 if __name__ == '__main__':
    127 
--> 128     hyperparams = get_all_params('grid_search')
    129 
    130     if 'slurm' in hyperparams and hyperparams.slurm:

/share/ctn/users/ccr2137/dev/behavenet/behavenet/fitting/hyperparam_utils.py in get_all_params(search_type, args)
     45     # Add parameters dependent on previous inputs
     46     namespace, extra = parser.parse_known_args(args)
---> 47     add_dependent_params(parser, namespace)
     48 
     49     return parser.parse_args(args)

/share/ctn/users/ccr2137/dev/behavenet/behavenet/fitting/hyperparam_utils.py in add_dependent_params(parser, namespace)
     82         if (arch_dict['ae_encoding_n_channels'][-1]
     83                 * arch_dict['ae_encoding_x_dim'][-1]
---> 84                 * arch_dict['ae_encoding_y_dim'][-1]) < namespace.n_ae_latents:
     85             raise ValueError('Bottleneck smaller than number of latents')
     86 

TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

It turns out that namespace.n_ae_latents is returning None, instead of the list in the json config. Any ideas? I could set a `default=value[0]` in :
https://github.com/ebatty/behavenet/blob/develop/behavenet/fitting/hyperparam_utils.py#L54
But not sure if that would break something else.

**Comment by themattinthehatt** [comment]
Hmmm we've had this problem before, I thought it was fixed :/ 

I can take a look at it later this afternoon.

**Comment by cxrodgers** [comment]
Oh, I hope I'm using the up to date versions of everything. I just checked I'm on the 'develop' branch of behavenet, pulled all recent changes, and checked that I have the versions in requirements.txt. 

```
behavenet                 0.0.2                     dev_0    <develop>
python                    3.7.2                h0371630_0  
ssm                       0.0.1                     dev_0    <develop>
test-tube                 0.7.3                    pypi_0    pypi
torch                     1.3.1                    pypi_0    pypi
```
I'm using this change to fix it for now:
https://github.com/cxrodgers/behavenet/commit/9cc89256ebc11b65d193499d5e8c174860f2d6a7
So no rush on this at all, because this workaround seems to work. 

Let me know if there's anything I can do to help. thanks!!

**Comment by themattinthehatt** [comment]
@yifr were you having this problem as well?

**Comment by yifr** [comment]
Yeah, at the time I ended up just removing the check for the time being, but you had a commit that was intended to solve it:

https://github.com/ebatty/behavenet/issues/11

**Comment by themattinthehatt** [comment]
@cxrodgers fixed this - it's a bit ugly but should work. Let me know if you have any problems with it!

**Comment by cxrodgers** [comment]
works, thanks!!
