### ISSUE TITLE
Problem with matplotlib backend on MacOS

### ISSUE THREAD

**Issue by adelaneh** [ebatty/behavenet#6]
When trying to train ARHMM using the following command:

`python behavenet/fitting/arhmm_grid_search.py --data_config ~/.behavenet/musall_vistrained_params.json --model_config ~/.behavenet/arhmm_model.json --training_config ~/.behavenet/arhmm_training.json --compute_config ~/.behavenet/arhmm_compute.json`

the following error appears:

`Traceback (most recent call last):
  File "behavenet/fitting/arhmm_grid_search.py", line 10, in <module>
    from behavenet.fitting.hyperparam_utils import get_all_params
  File "behavenet/fitting/hyperparam_utils.py", line 1, in <module>
    import commentjson
  File "anaconda3/envs/behavenet/lib/python3.7/site-packages/commentjson/__init__.py", line 1, in <module>
    from .commentjson import dump
  File "anaconda3/envs/behavenet/lib/python3.7/site-packages/commentjson/commentjson.py", line 55, in <module>
    serializer = Reconstructor(parser)
  File "anaconda3/envs/behavenet/lib/python3.7/site-packages/lark/reconstruct.py", line 92, in __init__
    assert parser.options.maybe_placeholders == False
AssertionError`

**Comment by adelaneh** [comment]
In file `behavenet/plotting/arhmm_utils.py` add the following two lines

`
import matplotlib
matplotlib.use('agg',warn=False, force=True)
`

before

`
import matplotlib.pyplot as plt
`

**Comment by themattinthehatt** [comment]
@adelaneh thanks for posting this. Do you have any idea why changing the matplotlib backend helps with this problem? The traceback seems opaque, but I would not have expected matplotlib to be involved.

**Comment by adelaneh** [comment]
@themattinthehatt I corrected the original comment to reflect the correct error message. I was getting multiple error messages at the time of posting this and ended up copying the wrong one here. Hope this makes it clear now.
