### ISSUE TITLE
n_trials not defined

### ISSUE THREAD

**Issue by nonsenseWHO** [ebatty/behavenet#7]
When I placed my data in the designated format and tried to run the hdf5 creation script, n_trials was undefined! Simple fix by using element count of imaging data list to define--just wanted to give ya a heads up

(ref: https://behavenet.readthedocs.io/en/latest/source/data_structure.html)

**Comment by themattinthehatt** [comment]
Thanks for the heads up! The documentation will be updated for the next release.
